### PR TITLE
fix for ConcurrentModificationException when using multidex

### PR DESCRIPTION
**Pull request by marcinpaszylk**
There's ConcurrentModificationException thrown when ArrayList is iterated. This should fix the problem.

### CODE REVIEW

**Comment by marcinpaszylk** [comment]
It's hard to test it, because it's not easily reproducible. It happens 1/20 times in Android projects with multidex support on logger stop method execution.
I don't know, how should I write unit tests for this fix.

**Comment by tony19** [comment]
Ok, gotcha.

**Comment by marcinpaszylk** [comment]
Could you tell me when next version of the lib will be released?

**Comment by tony19** [comment]
1.1.1-4 was released a couple days ago.

**Pull request merged**
