### PR TITLE
feat!: upgrade to slf4j 2.0.7

### LINKED ISSUE #249: No log is printed with Slf4j 2.x.x
## Description

I apply the slf4j version 2.0.3 in android project.
I tried to print log with debug, error level but nothing is printed. I check via logcat.

If I rollback to version 1.7.36, it works.

## Steps to reproduce

implementation("org.slf4j:slf4j-api:2.0.3")
implementation("com.github.tony19:logback-android:2.0.0")

## Environment

Android version : 9
Device : Huawei Nova 3i

### PR DESCRIPTION
**Pull request by tony19**
fix #249 
related #247

### CODE REVIEW

**Comment by abouquet** [comment]
Hi ! any followup on this fix ? :)

**Comment by tony19** [comment]
Sorry for the delay. The unit tests are failing from the upgrade, and I don't have an immediate solution.

**Comment by sebkur** [comment]
I've tried running the tests locally and am getting the same errors as in the CI.

I do get more details there though. For example for `MDCTest#test()` the CI only shows 

```
ch.qos.logback.classic.MDCTest > test FAILED
    junit.framework.ComparisonFailure: expected:<a> but was:<null>
        at junit.framework.Assert.assertEquals(Assert.java:100)
        at junit.framework.Assert.assertEquals(Assert.java:107)
        at ch.qos.logback.classic.MDCTest.test(MDCTest.java:40)
```

while locally, I also get the underlying:

```
Exception in thread "Thread-3" java.lang.UnsatisfiedLinkError: 'int libcore.io.Linux.getuid()'
	at libcore.io.Linux.getuid(Native Method)
	at libcore.io.ForwardingOs.getuid(ForwardingOs.java:387)
	at android.system.Os.getuid(Os.java:363)
	at android.os.Process.myUid(Process.java:865)
	at android.os.UserHandle.myUserId(UserHandle.java:552)
	at android.os.Environment.initForCurrentUser(Environment.java:167)
	at android.os.Environment.<clinit>(Environment.java:161)
	at ch.qos.logback.core.android.AndroidContextUtil.getMountedExternalStorageDirectoryPath(AndroidContextUtil.java:96)
	at ch.qos.logback.core.android.AndroidContextUtil.setupProperties(AndroidContextUtil.java:59)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:125)
	at org.slf4j.impl.LoggerServiceProvider.initializeLoggerContext(LoggerServiceProvider.java:67)
	at org.slf4j.impl.LoggerServiceProvider.initialize(LoggerServiceProvider.java:58)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:453)
	at org.slf4j.MDC.<clinit>(MDC.java:91)
	at ch.qos.logback.classic.MDCTestThread.run(MDCTestThread.java:34)
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class org.slf4j.MDC
	at ch.qos.logback.classic.MDCTestThread.run(MDCTestThread.java:34)
```

A similar message also appears in the CI log:

```
ch.qos.logback.classic.AsyncAppenderTest > eventWasPreparedForDeferredProcessing FAILED
    java.lang.UnsatisfiedLinkError: 'int libcore.io.Linux.getuid()'
        at libcore.io.Linux.getuid(Native Method)
        at libcore.io.ForwardingOs.getuid(ForwardingOs.java:387)
        at android.system.Os.getuid(Os.java:363)
        at android.os.Process.myUid(Process.java:865)
        at android.os.UserHandle.myUserId(UserHandle.java:552)
        at android.os.Environment.initForCurrentUser(Environment.java:167)
        at android.os.Environment.<clinit>(Environment.java:161)
        at ch.qos.logback.core.android.AndroidContextUtil.getMountedExternalStorageDirectoryPath(AndroidContextUtil.java:96)
        at ch.qos.logback.core.android.AndroidContextUtil.setupProperties(AndroidContextUtil.java:59)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:125)
        at org.slf4j.impl.LoggerServiceProvider.initializeLoggerContext(LoggerServiceProvider.java:67)
        at org.slf4j.impl.LoggerServiceProvider.initialize(LoggerServiceProvider.java:58)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:453)
        at org.slf4j.MDC.<clinit>(MDC.java:91)
        at ch.qos.logback.classic.AsyncAppenderTest.eventWasPreparedForDeferredProcessing(AsyncAppenderTest.java:56)
```

I've added some stdout logging to `AndroidContextUtil.getMountedExternalStorageDirectoryPath` and ran the MDCTest on branch `main`, where it appears this code does not get called. It seems that the call to `LoggerFactory.getProvider()` is new in the updated version of slf4j. `getProvider()` is annotated as `since 1.8.0` in slf4j.

Generally, I'm wondering: how are the unit tests supposed to run on a regular linux box? Don't we need to run them on Android and isn't it rather expected that tests could fail if Android APIs are used in the code of logback-android? Or is there any utility in place to substitute android APIs with something that works on regular Linux for testing that maybe needs to be modified for this upgrade here?

**Comment by sebkur** [comment]
ah, sorry, this is running on the Android container on CircleCI, so I guess it does not make too much sense to try running the tests locally.

**Comment by DevDengChao** [comment]
🎉

**Pull request merged**
